default: &default
  maximum_cookies_allowed_in_an_oven: 12
development:
  <<: *default
  cookie_preparation_job_delay: <%= 1.minutes %>
  cookie_polling_interval: <%= 10.seconds %>
test:
  <<: *default
  cookie_preparation_job_delay: <%= 1.second %>
  cookie_polling_interval: <%= 1.second %>
production:
  <<: *default
  cookie_preparation_job_delay: <%= 5.minutes %>
  cookie_polling_interval: <%= 1.minute %>
